### ISSUE TITLE
Se queda en la pantalla waitPlayer

### ISSUE THREAD

**Issue by alexismunoz1** [ayrton08/dwf-m6-desafio#1]
Buenas Ayrton como va?
El juego se queda en la pantalla `waitPlayer` y no avanza
![Captura de pantalla de 2022-05-20 16-11-55](https://user-images.githubusercontent.com/77214476/169596376-5622b89c-f150-47de-bb89-d2e855f5dca8.png)
Pasa lo mismo con ambos jugadores

**Comment by ayrton08** [comment]
Hola Alexis.. gracias por chequear el proyecto, ahí lo volví a correr de forma local y el deploy y funciona bien.. no se me tilda en esa page, pero lo voy a chequear con más detenimiento, alguna sugerencia de por qué podría pasar eso?
