### ISSUE TITLE
Se tilda al momento de apretar para jugar

### ISSUE THREAD

**Issue by giulianaerro** [ayrton08/dwf-m6-desafio#2]
Hola ayrton! estuve probando tu juego, me re gusta tu diseño, va todo genial hasta el momento que debo apretar alguna mano para poder jugar, no funciona: 

![Captura de pantalla de 2022-05-24 11-57-42](https://user-images.githubusercontent.com/73187805/170067987-2ca67a2b-5ac2-4e66-b8c4-73f2982f22ed.png)

**Comment by ayrton08** [comment]
Buenas, primero que nada muchas gracias por la ayuda y gracias al aporte logre encontre el error, yo estaba probando la app en dos "ventanas" diferentes entonces me estaba funcionando bien por la data en el localstore no se pisaba, pero probando en dos "pestañas" diferentes la data se sobreescribia y pasaba lo que indicaste muy bien @alexismunoz1, asi que cambie el flujo de la informacion al setear el indentificador del player y quedo funcionando

**Comment by FerDR89** [comment]
Buenas Ayrton,
Ahí probé la app y funca normal.
Éxitos en el siguiente modulo.
